language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

install:
  - composer require php-coveralls/php-coveralls:"^2.1" phpunit/phpcov:">=3.0"
  - composer install

after_success:
  - travis_retry php vendor/bin/php-coveralls
